### ISSUE TITLE
discord.py 2 broke discord-irc-sync

### ISSUE THREAD

**Issue by JulienPalard** [Hackndo/discord-irc-sync#12]
Looks like the `intents` Client argument is now mandatory, I'm getting:

```pytb
Traceback (most recent call last):
   File "/home/discord-irc-sync/src/discord-irc-sync.py", line 16, in <module>
     discord_client = DiscordClient(settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/discord-irc-sync/src/src/discordclient.py", line 48, in __init__
     super().__init__()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'
```

While it works with `discord.py<2` (which gives discord.py==1.7.3)

**Comment by JulienPalard** [comment]
Thanks for working on a fix!

I updated my instance, but now messages from Discord are empty, I'll open another issue about it.

**Comment by Hackndo** [comment]
Should be fixed :)
